version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vedanta-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - vedanta-network
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  vedanta-network:
    external: true
    name: vedanta-network
